export const SYSTEM_NODE_LABELS_UPDATE_START = 'SYSTEM/NODE_LABELS_UPDATE_START';
export const SYSTEM_NODE_LABELS_UPDATE_END = 'SYSTEM/NODE_LABELS_UPDATE_END';
export const SYSTEM_EDGE_TYPES_UPDATE_START = 'SYSTEM/EDGE_TYPES_UPDATE_START';
export const SYSTEM_EDGE_TYPES_UPDATE_END = 'SYSTEM/EDGE_TYPES_UPDATE_END';
export const SYSTEM_PROPERTIES_UPDATE_START = 'SYSTEM/NODE_PROPERTIES_START';
export const SYSTEM_PROPERTIES_UPDATE_END = 'SYSTEM/NODE_PROPERTIES_END';
