export const CYTOSCAPEJS_FULL = 'CYTOSCAPEJS/FULL';
export const CYTOSCAPEJS_CYPHER_CHANGE = 'CYTOSCAPEJS/CYPHER_CHANGE';
export const CYTOSCAPEJS_UNFULL = 'CYTOSCAPEJS/UNFULL';
export const CYTOSCAPEJS_NODE_MESSAGE = 'CYTOSCAPEJS/NODE_MESSAGE';