export const NEO4JGRAPH_FULL = 'NEO4JGRAPH/FULL';
export const NEO4JGRPH_CYPHER_CHANGE = 'NEO4JGRPH/CYPHER_CHANGE';
export const NEO4JGRAPH_UNFULL = 'NEO4JGRAPH/UNFULL';
export const NEO4JGRAPH_NODE_MESSAGE = 'NEO4JGRAPH/NODE_MESSAGE';